#Importing Necessary Library

In [0]:
from pandas import read_csv
import numpy as np
import pandas as pd
import scipy 
from sklearn.preprocessing import MinMaxScaler;
from sklearn.preprocessing import StandardScaler;
from sklearn.preprocessing import Normalizer;
from sklearn.preprocessing import Binarizer;

In [2]:
dataset = pd.read_csv('forestfires.csv')
print(dataset.shape)

(517, 13)


#Data Visualization

In [3]:
print(dataset.head())

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0


In [4]:
print(dataset.describe())

                X           Y        FFMC  ...        wind        rain         area
count  517.000000  517.000000  517.000000  ...  517.000000  517.000000   517.000000
mean     4.669246    4.299807   90.644681  ...    4.017602    0.021663    12.847292
std      2.313778    1.229900    5.520111  ...    1.791653    0.295959    63.655818
min      1.000000    2.000000   18.700000  ...    0.400000    0.000000     0.000000
25%      3.000000    4.000000   90.200000  ...    2.700000    0.000000     0.000000
50%      4.000000    4.000000   91.600000  ...    4.000000    0.000000     0.520000
75%      7.000000    5.000000   92.900000  ...    4.900000    0.000000     6.570000
max      9.000000    9.000000   96.200000  ...    9.400000    6.400000  1090.840000

[8 rows x 11 columns]


In [5]:
dataset.columns

Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')

In [6]:
dataset.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       517 non-null    int64  
 1   Y       517 non-null    int64  
 2   month   517 non-null    object 
 3   day     517 non-null    object 
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64  
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
 12  area    517 non-null    float64
dtypes: float64(8), int64(3), object(2)
memory usage: 52.6+ KB


In [7]:
dataset.dtypes

X          int64
Y          int64
month     object
day       object
FFMC     float64
DMC      float64
DC       float64
ISI      float64
temp     float64
RH         int64
wind     float64
rain     float64
area     float64
dtype: object

#Checking Null Values

In [8]:
print((dataset[['X','Y','FFMC','DMC','DC','ISI','temp','RH','wind','rain','area']]==0).sum())

X         0
Y         0
FFMC      0
DMC       0
DC        0
ISI       1
temp      0
RH        0
wind      0
rain    509
area    247
dtype: int64


In [0]:
array = dataset.values

In [0]:
X = array[:,0:11]
Y = array[:,12]

In [11]:
X.shape

(517, 11)

In [12]:
Y.shape

(517,)

#Rescaling Data

In [0]:
scaler = MinMaxScaler(feature_range=(0,0.5))


In [14]:
rescaledX = scaler.fit_transform(X[:,4:12])
print(rescaledX)

[[0.43548387 0.04324604 0.0506626  ... 0.09646302 0.21176471 0.35      ]
 [0.46387097 0.05909717 0.38770963 ... 0.25401929 0.10588235 0.02777778]
 [0.46387097 0.07339766 0.39814706 ... 0.19935691 0.10588235 0.05      ]
 ...
 [0.40580645 0.095796   0.38565732 ... 0.30546624 0.32352941 0.35      ]
 [0.4883871  0.24965541 0.35581095 ... 0.37620579 0.15882353 0.2       ]
 [0.39225806 0.0032736  0.05793362 ... 0.15434084 0.09411765 0.22777778]]


In [0]:
np.set_printoptions(precision=3)

In [16]:
print(rescaledX[:,:])

[[0.435 0.043 0.051 ... 0.096 0.212 0.35 ]
 [0.464 0.059 0.388 ... 0.254 0.106 0.028]
 [0.464 0.073 0.398 ... 0.199 0.106 0.05 ]
 ...
 [0.406 0.096 0.386 ... 0.305 0.324 0.35 ]
 [0.488 0.25  0.356 ... 0.376 0.159 0.2  ]
 [0.392 0.003 0.058 ... 0.154 0.094 0.228]]


#Standardizing Data

In [0]:
scaler2 = StandardScaler().fit(X[:,4:12])

In [0]:
rescaledX2 = scaler2.transform(X[:,4:12])

In [19]:
np.set_printoptions(precision=3)
print(rescaledX[:,:])

[[0.435 0.043 0.051 ... 0.096 0.212 0.35 ]
 [0.464 0.059 0.388 ... 0.254 0.106 0.028]
 [0.464 0.073 0.398 ... 0.199 0.106 0.05 ]
 ...
 [0.406 0.096 0.386 ... 0.305 0.324 0.35 ]
 [0.488 0.25  0.356 ... 0.376 0.159 0.2  ]
 [0.392 0.003 0.058 ... 0.154 0.094 0.228]]


#Normalizing Data

In [0]:
scaler3 = Normalizer().fit(X[:,4:12])

In [0]:
normalizedX = scaler3.transform(X[:,4:12])

In [22]:
np.set_printoptions(precision=3)
print(normalizedX[:,:])

[[0.613 0.186 0.671 ... 0.058 0.363 0.048]
 [0.134 0.052 0.988 ... 0.027 0.049 0.001]
 [0.13  0.063 0.988 ... 0.021 0.047 0.002]
 ...
 [0.121 0.084 0.983 ... 0.031 0.103 0.01 ]
 [0.147 0.228 0.959 ... 0.04  0.066 0.006]
 [0.579 0.022 0.777 ... 0.086 0.226 0.033]]


#Binarize Data

In [0]:
binarizer = Binarizer(threshold=1).fit(X[:,4:12])

In [0]:
binarizedX = binarizer.transform(X[:,4:12])

In [25]:
np.set_printoptions(precision=3)
print(binarizedX[:,:])

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 0.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
